/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUserRouteRouteImport } from './routes/admin/user.route'
import { Route as AdminPostRouteRouteImport } from './routes/admin/post.route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserRouteRoute = AdminUserRouteRouteImport.update({
  id: '/admin/user',
  path: '/admin/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostRouteRoute = AdminPostRouteRouteImport.update({
  id: '/admin/post',
  path: '/admin/post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/post': typeof AdminPostRouteRoute
  '/admin/user': typeof AdminUserRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/post': typeof AdminPostRouteRoute
  '/admin/user': typeof AdminUserRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/post': typeof AdminPostRouteRoute
  '/admin/user': typeof AdminUserRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/post' | '/admin/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/post' | '/admin/user'
  id: '__root__' | '/' | '/admin/post' | '/admin/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPostRouteRoute: typeof AdminPostRouteRoute
  AdminUserRouteRoute: typeof AdminUserRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/admin/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/post': {
      id: '/admin/post'
      path: '/admin/post'
      fullPath: '/admin/post'
      preLoaderRoute: typeof AdminPostRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPostRouteRoute: AdminPostRouteRoute,
  AdminUserRouteRoute: AdminUserRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
