/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUserPageRouteImport } from './routes/admin/user.page'
import { Route as AdminPostPageRouteImport } from './routes/admin/post.page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserPageRoute = AdminUserPageRouteImport.update({
  id: '/admin/user/page',
  path: '/admin/user/page',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostPageRoute = AdminPostPageRouteImport.update({
  id: '/admin/post/page',
  path: '/admin/post/page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/post/page': typeof AdminPostPageRoute
  '/admin/user/page': typeof AdminUserPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/post/page': typeof AdminPostPageRoute
  '/admin/user/page': typeof AdminUserPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/post/page': typeof AdminPostPageRoute
  '/admin/user/page': typeof AdminUserPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/post/page' | '/admin/user/page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/post/page' | '/admin/user/page'
  id: '__root__' | '/' | '/admin/post/page' | '/admin/user/page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPostPageRoute: typeof AdminPostPageRoute
  AdminUserPageRoute: typeof AdminUserPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/page': {
      id: '/admin/user/page'
      path: '/admin/user/page'
      fullPath: '/admin/user/page'
      preLoaderRoute: typeof AdminUserPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/post/page': {
      id: '/admin/post/page'
      path: '/admin/post/page'
      fullPath: '/admin/post/page'
      preLoaderRoute: typeof AdminPostPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPostPageRoute: AdminPostPageRoute,
  AdminUserPageRoute: AdminUserPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
